#! /bin/bash
#SBATCH --time=01:00:00
#SBATCH -p short
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=ghoshs@montclair.edu
# Submit with e.g.  sbatch --array 1-13 <scriptname> to run multiple instances

echo -e "\n\n"
date
pwd
echo -e "\n\n"


echo $SLURM_ARRAY_TASK_ID
RA=`awk "NR==$SLURM_ARRAY_TASK_ID" sky_positions.txt|awk '{print $1}'`
DEC=`awk "NR==$SLURM_ARRAY_TASK_ID" sky_positions.txt|awk '{print $2}'`
echo 'RA of injection: '$RA '. Dec of injection: '$DEC

FRAME='frames/H-H1_STRAIN-1264069359-25-RA_'$RA'-DEC_'$DEC'.gwf'
CHANNEL='H1:SIM-STRAIN'
python get_slurm_time.py -ra $RA -dec $DEC -c inj_config.ini -ff $FRAME -o $CHANNEL

FRAME='frames/V-V1_STRAIN-1264069359-25-RA_'$RA'-DEC_'$DEC'.gwf'
CHANNEL='V1:SIM-STRAIN'
python get_slurm_time.py -ra $RA -dec $DEC -c inj_config.ini -ff $FRAME -o $CHANNEL

FRAME='frames/L-L1_STRAIN-1264069359-25-RA_'$RA'-DEC_'$DEC'.gwf'
CHANNEL='L1:SIM-STRAIN'
python get_slurm_time.py -ra $RA -dec $DEC -c inj_config.ini -ff $FRAME -o $CHANNEL

echo 'time for $RA _ $DEC written'
